### ISSUE TITLE
Widgets misaligned in Gnome 3.28

### ISSUE THREAD

**Issue by IBBoard** [JasonLG1979/gnome-shell-extensions-mediaplayer#448]
I've just upgraded to Gnome 3.28 (openSUSE Tumbleweed) and the widgets are all offset to the right. Everything used to be centralised. I'm guessing that some default CSS changed somewhere.

![mediaplayeralignment](https://user-images.githubusercontent.com/388582/37559725-a63f0426-2a22-11e8-951f-70a9a241b075.png)

**Comment by IBBoard** [comment]
I can't work out how to use LookingGlass to inspect the widgets, but I've managed to bodge together some CSS that hopefully shows something useful about the structure. The boxes on the left look like they shouldn't be necessary (but I'm guessing based on webdev and GTK3 work, not Gnome Shell extension knowledge!).

![mediaplayeralignmentoutlined](https://user-images.githubusercontent.com/388582/37559884-b222536c-2a25-11e8-95f0-52f974020812.png)

**Comment by glaubersm** [comment]
Confirmed on Arch Linux.

**Comment by JasonLG1979** [comment]
It's never been truly centered because of how menus are laid out in Shell widgets.

I have yet to update to GNOME 3.28. When I do I see what I can do to fix this. If I had to guess they changed some style class names.

**Comment by JasonLG1979** [comment]
@IBBoard St Widgets(GNOME Shell UI widgets) kinda suck and are very inflexible most specifically the menus. They are also basically impossible debug. Because of that most of the extension uses custom widgets that can be found here:

 https://github.com/JasonLG1979/gnome-shell-extensions-mediaplayer/blob/master/src/widget.js

To fix the issue I'll basically need to go though and make sure all the stock style class names are still valid and double check all the alignment params by hand.

This extension is getting a little bloated and long in the tooth. It would be nice to get rid of as much custom widgets/hacky workaround code as possible.

**Comment by JasonLG1979** [comment]
I've started a new MPRIS extension in the effort to maybe start fresh:

https://github.com/JasonLG1979/gnome-shell-extensions-mpris-indicator-button

The end goal of the new extension is to eventually more or less duplicate the Unity SoundMenu (minus the sound device controls). And to be as simple as possible with no config options.

![screenshot from 2018-04-03 11-43-03](https://user-images.githubusercontent.com/6667703/38263059-980a7182-3734-11e8-8868-6f540c585e39.png)

**Comment by IBBoard** [comment]
Does the MPRIS system include ratings? I looked into MPRIS once when getting Quod Libet to work with some MPRIS tools, but I can't remember which bits were and weren't in the standard and which were extensions.

The main thing that I use this extension for is rating tracks (and occasionally looking at the details). I've got keyboard shortcuts for play/pause and skipping, but not for rating!

**Comment by JasonLG1979** [comment]
The MPRIS spec supports getting ratings from players but not setting ratings. Setting ratings in this extension is a bit of a hack and requires player specific code.

**Comment by JasonLG1979** [comment]
Some players have dbus interfaces for setting ratings some we just use the command line.

**Comment by JasonLG1979** [comment]
No

**Comment by andyholmes** [comment]
[This came up](https://github.com/andyholmes/gnome-shell-extension-gsconnect/issues/44#issuecomment-377751194) in my extension as well, the offending commit was here:
* https://gitlab.gnome.org/GNOME/gnome-shell/commit/fb9db4e171778a63bd85ac6fde15b7acfdede2c2

I submitted an MR that was accepted yesterday, making it easier to address when it lands:
* https://gitlab.gnome.org/GNOME/gnome-shell/merge_requests/71

And here's a rough example of how I fixed it (also forward compatible with the MR which should make it in 3.28.1):
```css
/* Reset the margin/padding changes to 0 for the submenu item :first-child's */
.aggregate-menu .popup-sub-menu .custom-submenu-class :first-child {
    padding: 0;
    margin: 0;
}

/* Apply something like this to any :first-child that needs non-0 margin/padding */
.aggregate-menu .popup-sub-menu .custom-childitem-class:first-child {
    padding: 8px;
}
```

(credits due to the folks on my issue that helped track this down)

**Comment by IBBoard** [comment]
I can confirm that it fixes it for me for this extension as well (although it needs improving).

If I add:

    .aggregate-menu .popup-sub-menu  :first-child {
        padding: 0;
        margin: 0;
    }

to `.local/share/gnome-shell/extensions/mediaplayer@patapon.info/stylesheet.css` and restart Gnome Shell then everything appears pretty much centralised (although the prev/pause/next buttons are too close together)

**Comment by IBBoard** [comment]
It does appear to break the other submenus at the moment (slightly), but given that I almost never use the "Wired Connection" or user details submenus whereas I look at the media player multiple times a day then I'll live with it as an initial fix!

If I had a decent DOM inspector then I could do better than my second attempt!

**Comment by fcastilloec** [comment]
@IBBoard Thanks for that workaround!!! I also don't care too much about the submenus either, so it's a great fix. Nonetheless, if you have found a better way to fix this, do let us know, please! Thanks again for the great workaround.

**Comment by ImKK-000** [comment]
@IBBoard Thanks a lot. Your comment fixed me on Ubuntu 18.04.

**Comment by Zeka13** [comment]
plz fix in master

**Comment by NellyWhadsDev** [comment]
Is there a plan to submit this fix into master? Or is the approach non-ideal?

**Comment by bpresles** [comment]
In my case the workaround is not centralizing correctly, the elements are too much on the left (instead of being too much on the right before the workaround).

![image](https://user-images.githubusercontent.com/220623/41200127-2999a2ea-6c9f-11e8-9c65-0fb596c55a51.png)

**Comment by SamadiPour** [comment]
best fix was this one (from k3rnel):
```css
.panel-media-indicator .popup-sub-menu > * > * > :first-child,
.panel-media-indicator .popup-sub-menu > * > * > :last-child > :first-child,
.panel-media-indicator .popup-sub-menu > * > * > :last-child > :first-child > :first-child {
    margin:  0;
    padding: 0;
}
```

add it to:
>  ~/.local/share/gnome-shell/extensions/mediaplayer@patapon.info/stylesheet.css

here is the result

![untitled](https://user-images.githubusercontent.com/24422125/46813805-3dbd6680-cd84-11e8-9654-617ffca4e5f8.png)

**Comment by JasonLG1979** [comment]
Put in a pull request and I'll merge it.

**Comment by fcastilloec** [comment]
@SamadiPour I tried your fix but it didn't work on Ubuntu 18.04, here's what it looks like with your code:
![fix](https://user-images.githubusercontent.com/1280530/46822482-74718d80-cd40-11e8-96d0-0155f42eb5ac.png)
So far only @IBBoard has worked for me.

**Comment by IBBoard** [comment]
That's odd, because @SamadiPour's changes look just like mine, but with a different (more accurate) initial selector!

**Comment by SamadiPour** [comment]
@fcastilloec 
i'm on 18.04 also. gnome 3.28.
not sure why it didn't work for you
did you reset gnome?
press Alt+F2 write r press Enter

@IBBoard 
yeah exactly. changes are same but other submenus won't break. atleast it works fine for me.

**Comment by JasonLG1979** [comment]
It works if the extension is in indicator mode but not if the extension is in the system menu.

![screenshot from 2018-10-11 13-19-03](https://user-images.githubusercontent.com/6667703/46825131-7fd0b300-cd58-11e8-9135-19022bbef45f.png)
![screenshot from 2018-10-11 13-19-15](https://user-images.githubusercontent.com/6667703/46825132-7fd0b300-cd58-11e8-8f24-ffc8e62be217.png)

**Comment by SamadiPour** [comment]
@JasonLG1979 
Thanks for noticing
i played with code
and here is the final souloution
i can't pull request in master branch so please after approving it, change your code yourself
Thanks.  
@fcastilloec please try this one


```css
.panel-media-indicator .popup-sub-menu > * > * > :first-child,
.panel-media-indicator .popup-sub-menu > * > * > :last-child > :first-child,
.panel-media-indicator .popup-sub-menu > * > * > :last-child > :first-child > :first-child {
    margin:  0;
    padding: 0;
}
```

add it to:
>  ~/.local/share/gnome-shell/extensions/mediaplayer@patapon.info/stylesheet.css

then open this file:
>  ~/.local/share/gnome-shell/extensions/mediaplayer@patapon.info/extension.js

find this line:
```javascript
menu = Main.panel.statusArea.aggregateMenu.menu;
```
press enter and add this line after it
```javascript
 menu.actor.add_style_class_name('panel-media-indicator');
```
it shoulds look like this:

![screenshot](https://user-images.githubusercontent.com/24422125/46829292-3d37c680-cdaa-11e8-9283-011b58447c9f.png)


here is the result

![untitled](https://user-images.githubusercontent.com/24422125/46813805-3dbd6680-cd84-11e8-9654-617ffca4e5f8.png)

![screenshot from 2018-10-11 23-09-02](https://user-images.githubusercontent.com/24422125/46829497-da92fa80-cdaa-11e8-8121-7c6ea6124c26.png)
